### ISSUE TITLE
Mix.exs repository link links to `raxx`

### ISSUE THREAD

**Issue by Qqwy** [CrowdHailer/pachyderm#12]
In the [mix.exs](https://github.com/CrowdHailer/pachyderm/blob/master/mix.exs#L35) you link to the raxx repository rather than to this one.

This results in the link to Raxx being shown on the Hex.pm package page, which probably is not the intention :slightly_smiling_face: .

**Comment by CrowdHailer** [comment]
Fixed in 0.2.1. by #11 

(I don't see a way to push changes to the already published 0.2.0 version) But I think it's fine with the latest version pointing to the right place
